export const SET_SAVED_DISHES = 'SET_SAVED_DISHES'
export const SET_ALL_DISHES_NAMES = 'SET_ALL_DISHES_NAMES'
export const UPDATING_SAMPLE_REPORT = 'UPDATING_SAMPLE_REPORT'

// kitchen
export const SET_ORDERS_IN_KITCHEN = 'SET_ORDERS_IN_KITCHEN'
export const SET_NEW_ORDER_IN_KITCHEN = 'SET_NEW_ORDER_IN_KITCHEN'
export const UPDATE_ORDERS_IN_KITCHEN = 'UPDATE_ORDERS_IN_KITCHEN'
